name: angstrom
description: "A package for rapid prototyping of game worlds with a streaming API."
version: 0.0.2
homepage: https://github.com/chrisnorman7/angstrom

environment:
  sdk: ^3.10.2
  flutter: ">=1.17.0"

dependencies:
  backstreets_widgets: ^0.37.0
  flutter:
    sdk: flutter
  flutter_audio_games: ^0.50.1
  flutter_soloud: ^3.4.6
  json_annotation: ^4.9.0
  meta: ^1.17.0
  stts: ^1.2.6

dev_dependencies:
  build_runner: ^2.10.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.11.3

scripts:
  watch: dart run build_runner watch -d
  build: dart run build_runner build -d
